<template>
  <NucGridPage v-bind:gap="{'col':0,'row':0}" v-bind:rows="[1]"
    v-bind:schema="{'r0-c0':{'col':0,'row':0,'showIn':['xs','sm','md','lg'],'colSpan':1,'rowSpan':1}}"
    v-bind:columns="[1]" overflow="auto" v-bind:designMode="false" v-bind:minNsLimit="1080"
    v-bind:style="{'background':'#FFFFFF','paddingTop':'0px','paddingLeft':'0px','paddingRight':'0px','paddingBottom':'0px'}">
    <NucGridCell v-bind:wrap="true" v-bind:reverse="false" overflow="hidden" direction="column"
      v-bind:showInDevice="['xs','sm','md','lg']" verticalAlignment="top" horizontalAlignment="left"
      id="9bc5a50d-fd66-4421-9d89-f8ac5dd9048b" v-bind:col="0" v-bind:row="0" v-bind:colSpan="1" v-bind:rowSpan="1"
      v-bind:marginTop="0" v-bind:marginLeft="0" v-bind:marginRight="0" v-bind:marginBottom="0"
      v-bind:style="{'height':'auto','background':'transparent','paddingTop':'0px','borderColor':'','borderStyle':'solid','borderWidth':'0px','paddingLeft':'0px','borderRadius':'0px','paddingRight':'0px','paddingBottom':'0px','borderTopWidth':'0px','borderLeftWidth':'0px','borderRightWidth':'0px','borderBottomWidth':'0px','borderTopLeftRadius':'1px','borderTopRightRadius':'1px','borderBottomLeftRadius':'1px','borderBottomRightRadius':'1px'}"
      slot="r0-c0" area="r0-c0">
      <NucGroupElement top="-9.536082474226804%" left="0%" v-bind:snapX="false" v-bind:snapY="true"
        v-bind:isLock="false" bgColor="" position="absolute" ncTooltipText="" id="d3963ca5-9642-4bd5-aed1-daef58099cfe"
        v-bind:style="{'color':'#FFFFFF','width':'1050.75px','height':'637.5px','zIndex':2,'fontSize':'8.4375px','maxWidth':'','minWidth':'5.625','tabIndex':'-0.5625','boxShadow':'','fontStyle':'normal','marginTop':'0px','maxHeight':'','minHeight':'5.625','textAlign':'center','background':'','fontFamily':'Roboto-Regular,Roboto','fontWeight':'normal','lineHeight':'0.703125','marginLeft':'0px','paddingTop':'','textShadow':'','visibility':'visible','borderColor':'#767676','borderStyle':'solid','marginRight':'0px','paddingLeft':'','marginBottom':'0px','paddingRight':'','paddingBottom':'','borderTopWidth':'0.5625px','textDecoration':'none','borderLeftWidth':'0.5625px','borderRightWidth':'0.5625px','borderBottomWidth':'0.5625px','borderTopLeftRadius':'0px','borderTopRightRadius':'0px','borderBottomLeftRadius':'0px','borderBottomRightRadius':'0px'}">
        <WImage top="3.6556603773584904%" left="0%" v-bind:blank="false" v-bind:snapX="false" v-bind:snapY="false"
          v-bind:rounded="false" stretch="none"
          imageUrl="https://images01.nicepage.com/c461c07a441a5d220e8feb1a/506524b5fe295a46bca10adb/vcvv-min.jpg"
          position="absolute" v-bind:isEnabled="true" v-bind:thumbnail="false" blankColor="black"
          v-bind:aspectRatio="true" dataLoading="static" ncTooltipText="Please write a text to display in tooltip..."
          v-bind:nucalDataModel="{'type':'NSW','isList':false,'dynamic':true,'structure':[{'type':'string','update':{'type':'dataModelForDynamicType'},'propName':'imageUrl','displayName':'Value'}]}"
          ncClickBorderColor="black" ncHoverBorderColor="black" dataModelForDynamicType="string"
          id="4f37c404-d79a-45dc-9113-aa51ce33b907"
          v-bind:style="{'width':'1050px','height':'612.75px','zIndex':4,'maxWidth':'','minWidth':'','boxShadow':'','marginTop':'0px','maxHeight':'','minHeight':'','marginLeft':'0px','paddingTop':'0px','textShadow':'','visibility':'visible','borderColor':'#4B74FF','borderStyle':'solid','marginRight':'0px','paddingLeft':'0px','marginBottom':'0px','paddingRight':'0px','paddingBottom':'0px','borderTopWidth':'0px','borderLeftWidth':'0px','borderRightWidth':'0px','borderBottomWidth':'0px','borderTopLeftRadius':'0px','borderTopRightRadius':'0px','borderBottomLeftRadius':'0px','borderBottomRightRadius':'0px'}"/>
        <WLabel top="22.34567995424624%" left="32.51736323038737%" text="PC gaming news," v-bind:snapX="false"
          v-bind:snapY="false" theme="theme--light01" position="absolute" ncTypography="custom" ncTooltipText=""
          v-bind:nucalDataModel="{'type':'NSW','isList':false,'dynamic':false,'structure':[{'type':'string','propName':'text','displayName':'Value'}]}"
          id="073821d5-93bb-43ff-ab70-24b4c8cd2071"
          v-bind:style="{'color':'#ffffff','width':'','height':'','zIndex':5,'fontSize':'42.1875px','maxWidth':'','minWidth':'','fontStyle':'normal','marginTop':'0px','maxHeight':'','minHeight':'','textAlign':'left','fontFamily':'Montserrat-Regular,Montserrat','fontWeight':'normal','lineHeight':'0.7874999999999999','marginLeft':'0px','paddingTop':'0px','textShadow':'','visibility':'visible','marginRight':'0px','paddingLeft':'0px','marginBottom':'0px','paddingRight':'0px','paddingBottom':'0px','textDecoration':'none'}"/>
        <WLabel top="30.679013287579572%" left="29.288196563720703%" text="reviews, and guides" v-bind:snapX="false"
          v-bind:snapY="false" theme="theme--light01" position="absolute" ncTypography="custom" ncTooltipText=""
          v-bind:nucalDataModel="{'type':'NSW','isList':false,'dynamic':false,'structure':[{'type':'string','propName':'text','displayName':'Value'}]}"
          id="9d55b96f-89b6-4661-9b30-430a890fe65f"
          v-bind:style="{'color':'#ffffff','width':'','height':'','zIndex':6,'fontSize':'45px','maxWidth':'','minWidth':'','fontStyle':'normal','marginTop':'0px','maxHeight':'','minHeight':'','textAlign':'left','fontFamily':'Montserrat-Regular,Montserrat','fontWeight':'normal','lineHeight':'0.7874999999999999','marginLeft':'0px','paddingTop':'0px','textShadow':'','visibility':'visible','marginRight':'0px','paddingLeft':'0px','marginBottom':'0px','paddingRight':'0px','paddingBottom':'0px','textDecoration':'none'}"/>
        <WBoxColorAdvertisement top="0%" left="0%" v-bind:blank="true" v-bind:snapX="false" v-bind:snapY="false"
          imgSrc="" v-bind:overlay="true" cardText="" position="absolute" bgVariant="primary" changeColor="#3F2D57"
          textVariant="white"
          v-bind:nucalDataModel="{'type':'NSW','isList':false,'dynamic':false,'structure':[{'type':'string','propName':'imgSrc','displayName':'ImageUrl'},{'type':'string','propName':'cardText','displayName':'Value'}]}"
          verticalPosition="align-items-center" horizontalPosition="justify-content-center"
          id="5351eb67-bb63-4b4f-8aca-22506885205d"
          v-bind:style="{'width':'1080px','height':'55.125px','zIndex':7,'maxWidth':'','minWidth':'','marginTop':'0px','maxHeight':'','minHeight':'','marginLeft':'0px','paddingTop':'0px','marginRight':'0px','paddingLeft':'0px','marginBottom':'0px','paddingRight':'0px','paddingBottom':'0px'}"/>
        <WOutlineSecondaryButton tag="button" top="43.76528117359413%" left="33.61945636623748%" v-bind:pill="false"
          size="md" text="about us" type="button" v-bind:block="false" color="#FFFFFF" v-bind:snapX="false"
          v-bind:snapY="false" theme="theme--light01" v-bind:squared="false" variant="outline-secondary"
          position="absolute" v-bind:isEnabled="true" background="" borderColor="#6C757D" ncTypography="custom"
          v-bind:resetTrigger="false" ncTooltipText="" verticalWidth="60px"
          v-bind:nucalDataModel="{'type':'NSW','isList':false,'dynamic':false,'structure':[{'type':'string','propName':'text','displayName':'Value'}]}"
          verticalHeight="60px" horizontalWidth="72.4479px" horizontalHeight="37.5347px" ncClickFontColor="#FFFFFF"
          ncFocusFontColor="#FFFFFF" ncHoverFontColor="#FFFFFF" ncClickBorderColor="#4285f4"
          ncDisableFontColor="#FFFFFF" ncFocusBorderColor="#4285f4" ncHoverBorderColor="#4285f4"
          ncDisableBorderColor="transparent" ncClickBackgroundColor="#4285f4" ncFocusBackgroundColor="#4285f4"
          ncHoverBackgroundColor="#4285f4" ncDisableBackgroundColor="#969696" id="e0554423-b28c-4763-93f7-a64a8025a5ae"
          v-bind:style="{'width':'73.5px','height':'27.75px','zIndex':8,'fontSize':'12.375px','maxWidth':'','minWidth':'','tabIndex':'0px','boxShadow':'','fontStyle':'normal','marginTop':'0px','maxHeight':'','minHeight':'','textAlign':'center','fontFamily':'OpenSans-Regular,Open Sans','fontWeight':'normal','lineHeight':'0.7874999999999999','marginLeft':'0px','paddingTop':'','textShadow':'','visibility':'visible','borderStyle':'none','marginRight':'0px','paddingLeft':'','marginBottom':'0px','paddingRight':'','paddingBottom':'','borderTopWidth':'0.5625px','textDecoration':'none','borderLeftWidth':'0.5625px','borderRightWidth':'0.5625px','horizontalHeight':'21.11326875px','borderBottomWidth':'0.5625px','borderTopLeftRadius':'2.25px','borderTopRightRadius':'2.25px','borderBottomLeftRadius':'2.25px','borderBottomRightRadius':'2.25px'}"/>
        <WOutlineSecondaryButton tag="button" top="43.76528117359413%" left="40.772532188841204%" v-bind:pill="false"
          size="md" text="news" type="button" v-bind:block="false" color="#FFFFFF" v-bind:snapX="false"
          v-bind:snapY="false" theme="theme--light01" v-bind:squared="false" variant="outline-secondary"
          position="absolute" v-bind:isEnabled="true" background="" borderColor="#6C757D" ncTypography="custom"
          v-bind:resetTrigger="false" ncTooltipText="" verticalWidth="60px"
          v-bind:nucalDataModel="{'type':'NSW','isList':false,'dynamic':false,'structure':[{'type':'string','propName':'text','displayName':'Value'}]}"
          verticalHeight="60px" horizontalWidth="72.4479px" horizontalHeight="37.5347px" ncClickFontColor="#FFFFFF"
          ncFocusFontColor="#FFFFFF" ncHoverFontColor="#FFFFFF" ncClickBorderColor="#4285f4"
          ncDisableFontColor="#FFFFFF" ncFocusBorderColor="#4285f4" ncHoverBorderColor="#4285f4"
          ncDisableBorderColor="transparent" ncClickBackgroundColor="#4285f4" ncFocusBackgroundColor="#4285f4"
          ncHoverBackgroundColor="#4285f4" ncDisableBackgroundColor="#969696" id="ab59c5c4-17c8-4e8d-8caa-f6ee254ae109"
          v-bind:style="{'width':'58.5px','height':'27.75px','zIndex':9,'fontSize':'12.375px','maxWidth':'','minWidth':'','tabIndex':'0px','boxShadow':'','fontStyle':'normal','marginTop':'0px','maxHeight':'','minHeight':'','textAlign':'center','fontFamily':'OpenSans-Regular,Open Sans','fontWeight':'normal','lineHeight':'0.7874999999999999','marginLeft':'0px','paddingTop':'','textShadow':'','visibility':'visible','borderStyle':'none','marginRight':'0px','paddingLeft':'','marginBottom':'0px','paddingRight':'','paddingBottom':'','borderTopWidth':'0.5625px','textDecoration':'none','borderLeftWidth':'0.5625px','borderRightWidth':'0.5625px','horizontalHeight':'21.11326875px','borderBottomWidth':'0.5625px','borderTopLeftRadius':'2.25px','borderTopRightRadius':'2.25px','borderBottomLeftRadius':'2.25px','borderBottomRightRadius':'2.25px'}"/>
        <WOutlineSecondaryButton tag="button" top="43.64303178484108%" left="47.13876967095851%" v-bind:pill="false"
          size="md" text="reviews" type="button" v-bind:block="false" color="#FFFFFF" v-bind:snapX="false"
          v-bind:snapY="false" theme="theme--light01" v-bind:squared="false" variant="outline-secondary"
          position="absolute" v-bind:isEnabled="true" background="" borderColor="#6C757D" ncTypography="custom"
          v-bind:resetTrigger="false" ncTooltipText="" verticalWidth="60px"
          v-bind:nucalDataModel="{'type':'NSW','isList':false,'dynamic':false,'structure':[{'type':'string','propName':'text','displayName':'Value'}]}"
          verticalHeight="60px" horizontalWidth="72.4479px" horizontalHeight="37.5347px" ncClickFontColor="#FFFFFF"
          ncFocusFontColor="#FFFFFF" ncHoverFontColor="#FFFFFF" ncClickBorderColor="#4285f4"
          ncDisableFontColor="#FFFFFF" ncFocusBorderColor="#4285f4" ncHoverBorderColor="#4285f4"
          ncDisableBorderColor="transparent" ncClickBackgroundColor="#4285f4" ncFocusBackgroundColor="#4285f4"
          ncHoverBackgroundColor="#4285f4" ncDisableBackgroundColor="#969696" id="68e6479a-839b-43c6-9a96-7315b6caf766"
          v-bind:style="{'width':'64.5px','height':'27.75px','zIndex':10,'fontSize':'12.375px','maxWidth':'','minWidth':'','tabIndex':'0px','boxShadow':'','fontStyle':'normal','marginTop':'0px','maxHeight':'','minHeight':'','textAlign':'center','fontFamily':'OpenSans-Regular,Open Sans','fontWeight':'normal','lineHeight':'0.7874999999999999','marginLeft':'0px','paddingTop':'','textShadow':'','visibility':'visible','borderStyle':'none','marginRight':'0px','paddingLeft':'','marginBottom':'0px','paddingRight':'','paddingBottom':'','borderTopWidth':'0.5625px','textDecoration':'none','borderLeftWidth':'0.5625px','borderRightWidth':'0.5625px','horizontalHeight':'21.11326875px','borderBottomWidth':'0.5625px','borderTopLeftRadius':'2.25px','borderTopRightRadius':'2.25px','borderBottomLeftRadius':'2.25px','borderBottomRightRadius':'2.25px'}"/>
        <WOutlineSecondaryButton tag="button" top="43.64303178484108%" left="54.005722460658085%" v-bind:pill="false"
          size="md" text="articles" type="button" v-bind:block="false" color="#FFFFFF" v-bind:snapX="false"
          v-bind:snapY="false" theme="theme--light01" v-bind:squared="false" variant="outline-secondary"
          position="absolute" v-bind:isEnabled="true" background="" borderColor="#6C757D" ncTypography="custom"
          v-bind:resetTrigger="false" ncTooltipText="" verticalWidth="60px"
          v-bind:nucalDataModel="{'type':'NSW','isList':false,'dynamic':false,'structure':[{'type':'string','propName':'text','displayName':'Value'}]}"
          verticalHeight="60px" horizontalWidth="72.4479px" horizontalHeight="37.5347px" ncClickFontColor="#FFFFFF"
          ncFocusFontColor="#FFFFFF" ncHoverFontColor="#FFFFFF" ncClickBorderColor="#4285f4"
          ncDisableFontColor="#FFFFFF" ncFocusBorderColor="#4285f4" ncHoverBorderColor="#4285f4"
          ncDisableBorderColor="transparent" ncClickBackgroundColor="#4285f4" ncFocusBackgroundColor="#4285f4"
          ncHoverBackgroundColor="#4285f4" ncDisableBackgroundColor="#969696" id="7a08383c-6b16-49a0-84e6-229677697da0"
          v-bind:style="{'width':'66px','height':'27.75px','zIndex':11,'fontSize':'12.375px','maxWidth':'','minWidth':'','tabIndex':'0px','boxShadow':'','fontStyle':'normal','marginTop':'0px','maxHeight':'','minHeight':'','textAlign':'center','fontFamily':'OpenSans-Regular,Open Sans','fontWeight':'normal','lineHeight':'0.7874999999999999','marginLeft':'0px','paddingTop':'','textShadow':'','visibility':'visible','borderStyle':'none','marginRight':'0px','paddingLeft':'','marginBottom':'0px','paddingRight':'','paddingBottom':'','borderTopWidth':'0.5625px','textDecoration':'none','borderLeftWidth':'0.5625px','borderRightWidth':'0.5625px','horizontalHeight':'21.11326875px','borderBottomWidth':'0.5625px','borderTopLeftRadius':'2.25px','borderTopRightRadius':'2.25px','borderBottomLeftRadius':'2.25px','borderBottomRightRadius':'2.25px'}"/>
        <WOutlineSecondaryButton tag="button" top="43.73457166883681%" left="60.59027989705404%" v-bind:pill="false"
          size="md" text="future" type="button" v-bind:block="false" color="#FFFFFF" v-bind:snapX="false"
          v-bind:snapY="false" theme="theme--light01" v-bind:squared="false" variant="outline-secondary"
          position="absolute" v-bind:isEnabled="true" background="" borderColor="#6C757D" ncTypography="custom"
          v-bind:resetTrigger="false" ncTooltipText="" verticalWidth="60px"
          v-bind:nucalDataModel="{'type':'NSW','isList':false,'dynamic':false,'structure':[{'type':'string','propName':'text','displayName':'Value'}]}"
          verticalHeight="60px" horizontalWidth="72.4479px" horizontalHeight="37.5347px" ncClickFontColor="#FFFFFF"
          ncFocusFontColor="#FFFFFF" ncHoverFontColor="#FFFFFF" ncClickBorderColor="#4285f4"
          ncDisableFontColor="#FFFFFF" ncFocusBorderColor="#4285f4" ncHoverBorderColor="#4285f4"
          ncDisableBorderColor="transparent" ncClickBackgroundColor="#4285f4" ncFocusBackgroundColor="#4285f4"
          ncHoverBackgroundColor="#4285f4" ncDisableBackgroundColor="#969696" id="c5ca3a0b-11b5-4f1d-944c-9177b67dff23"
          v-bind:style="{'width':'60.1875px','height':'27.5625px','zIndex':12,'fontSize':'12.375px','maxWidth':'','minWidth':'','tabIndex':'0px','boxShadow':'','fontStyle':'normal','marginTop':'0px','maxHeight':'','minHeight':'','textAlign':'center','fontFamily':'OpenSans-Regular,Open Sans','fontWeight':'normal','lineHeight':'0.7874999999999999','marginLeft':'0px','paddingTop':'','textShadow':'','visibility':'visible','borderStyle':'none','marginRight':'0px','paddingLeft':'','marginBottom':'0px','paddingRight':'','paddingBottom':'','borderTopWidth':'0.5625px','textDecoration':'none','borderLeftWidth':'0.5625px','borderRightWidth':'0.5625px','horizontalHeight':'21.11326875px','borderBottomWidth':'0.5625px','borderTopLeftRadius':'2.25px','borderTopRightRadius':'2.25px','borderBottomLeftRadius':'2.25px','borderBottomRightRadius':'2.25px'}"/>
        <WImage top="2.067901470043041%" left="14.288196563720703%" v-bind:blank="false" v-bind:snapX="false"
          v-bind:snapY="false" v-bind:rounded="false" stretch="none"
          imageUrl="https://assets.website-files.com/60d124942562f25d199e9a69/617cbb067de75b2457678b1b_game-x-logo-webflow-template.svg"
          position="absolute" v-bind:isEnabled="true" v-bind:thumbnail="false" blankColor="black"
          v-bind:aspectRatio="true" dataLoading="static" ncTooltipText="Please write a text to display in tooltip..."
          v-bind:nucalDataModel="{'type':'NSW','isList':false,'dynamic':true,'structure':[{'type':'string','update':{'type':'dataModelForDynamicType'},'propName':'imageUrl','displayName':'Value'}]}"
          ncClickBorderColor="black" ncHoverBorderColor="black" dataModelForDynamicType="string"
          id="f61bf531-9cd1-4eb7-9630-f4f635c07142"
          v-bind:style="{'width':'113.625px','height':'23.625px','zIndex':15,'maxWidth':'','minWidth':'','boxShadow':'','marginTop':'0px','maxHeight':'','minHeight':'','marginLeft':'0px','paddingTop':'0px','textShadow':'','visibility':'visible','borderColor':'#4B74FF','borderStyle':'solid','marginRight':'0px','paddingLeft':'0px','marginBottom':'0px','paddingRight':'0px','paddingBottom':'0px','borderTopWidth':'0px','borderLeftWidth':'0px','borderRightWidth':'0px','borderBottomWidth':'0px','borderTopLeftRadius':'0px','borderTopRightRadius':'0px','borderBottomLeftRadius':'0px','borderBottomRightRadius':'0px'}"/>
        <WIconButton tag="button" top="2.4382718404134116%" icon="fas fa-bars" left="86.84027989705403%"
          v-bind:pill="false" size="md" text="   " type="button" v-bind:block="false" color="#FFFFFF"
          v-bind:snapX="false" v-bind:snapY="false" theme="theme--light01" v-bind:squared="false" variant="secondary"
          fontSize="12px" position="absolute" fontStyle="normal" iconColor="#ffffff" v-bind:isEnabled="true"
          background="#3f2d57" fontFamily="OpenSans-Bold,Open Sans" fontWeight="400" layoutMode="left-to-right"
          lineHeight="1.2" textShadow="" borderColor="#6C757D" iconFontSize="25px" ncTypography="body1"
          iconAlignment="center" iconFontStyle="default" ncTooltipText="" verticalWidth="" iconFontFamily="font-awesome"
          v-bind:nucalDataModel="{'type':'NSW','isList':false,'dynamic':false,'structure':[{'type':'string','propName':'text','displayName':'Value'}]}"
          textDecoration="none" verticalHeight="" horizontalWidth="" horizontalHeight="" ncClickFontColor="#FFFFFF"
          ncFocusFontColor="#FFFFFF" ncHoverFontColor="#FFFFFF" verticalMinWidth="40px" verticalMinHeight="60px"
          horizontalMinWidth="96px" ncClickBorderColor="#4285f4" ncDisableFontColor="#FFFFFF"
          ncFocusBorderColor="#4285f4" ncHoverBorderColor="#4285f4" buttonTextAlignment="center"
          horizontalMinHeight="30px" ncDisableBorderColor="#4285f4" ncClickBackgroundColor="#4285f4"
          ncFocusBackgroundColor="#4285f4" ncHoverBackgroundColor="#4285f4" ncDisableBackgroundColor="#4285f4"
          id="e4f0ec47-34ae-49b9-9f71-765a9ea407fb"
          v-bind:style="{'width':'27.5625px','height':'27px','zIndex':16,'maxWidth':'','minWidth':'5.625px','tabIndex':'0px','boxShadow':'','marginTop':'','maxHeight':'','marginLeft':'','paddingTop':'','visibility':'visible','borderStyle':'none','marginRight':'','paddingLeft':'','marginBottom':'','paddingRight':'','hasDesignMode':true,'paddingBottom':'','borderTopWidth':'0.5625px','borderLeftWidth':'0.5625px','borderRightWidth':'0.5625px','borderBottomWidth':'0.5625px','borderTopLeftRadius':'2.25px','borderTopRightRadius':'2.25px','borderBottomLeftRadius':'2.25px','borderBottomRightRadius':'2.25px'}"/>
        <WIconButton tag="button" top="2.317073170731707%" icon="fas fa-shopping-cart" left="83.5%" v-bind:pill="false"
          size="md" text="   " type="button" v-bind:block="false" color="#FFFFFF" v-bind:snapX="false"
          v-bind:snapY="false" theme="theme--light01" v-bind:squared="false" variant="secondary" fontSize="12px"
          position="absolute" fontStyle="normal" iconColor="#ffffff" v-bind:isEnabled="true" background="#3f2d57"
          fontFamily="OpenSans-Bold,Open Sans" fontWeight="400" layoutMode="left-to-right" lineHeight="1.2"
          textShadow="" borderColor="#6C757D" iconFontSize="20px" ncTypography="body1" iconAlignment="center"
          iconFontStyle="default" ncTooltipText="" verticalWidth="" iconFontFamily="font-awesome"
          v-bind:nucalDataModel="{'type':'NSW','isList':false,'dynamic':false,'structure':[{'type':'string','propName':'text','displayName':'Value'}]}"
          textDecoration="none" verticalHeight="" horizontalWidth="" horizontalHeight="" ncClickFontColor="#FFFFFF"
          ncFocusFontColor="#FFFFFF" ncHoverFontColor="#FFFFFF" verticalMinWidth="40px" verticalMinHeight="60px"
          horizontalMinWidth="96px" ncClickBorderColor="#4285f4" ncDisableFontColor="#FFFFFF"
          ncFocusBorderColor="#4285f4" ncHoverBorderColor="#4285f4" buttonTextAlignment="center"
          horizontalMinHeight="30px" ncDisableBorderColor="#4285f4" ncClickBackgroundColor="#4285f4"
          ncFocusBackgroundColor="#4285f4" ncHoverBackgroundColor="#4285f4" ncDisableBackgroundColor="#4285f4"
          id="ffafd9cc-2d8d-4ef4-a42d-aeda138455e6"
          v-bind:style="{'width':'27.5625px','height':'27px','zIndex':17,'maxWidth':'','minWidth':'5.625px','tabIndex':'0px','boxShadow':'','marginTop':'','maxHeight':'','marginLeft':'','paddingTop':'','visibility':'visible','borderStyle':'none','marginRight':'','paddingLeft':'','marginBottom':'','paddingRight':'','hasDesignMode':true,'paddingBottom':'','borderTopWidth':'0.5625px','borderLeftWidth':'0.5625px','borderRightWidth':'0.5625px','borderBottomWidth':'0.5625px','borderTopLeftRadius':'2.25px','borderTopRightRadius':'2.25px','borderBottomLeftRadius':'2.25px','borderBottomRightRadius':'2.25px'}"/>
        <WOutlineSecondaryButton tag="button" top="1.8337408312958434%" left="37.05293276108727%" v-bind:pill="false"
          size="md" text="HOME" type="button" v-bind:block="false" color="#FFFFFF" v-bind:snapX="false"
          v-bind:snapY="false" theme="theme--light01" v-bind:squared="false" variant="outline-secondary"
          position="absolute" v-bind:isEnabled="true" background="" borderColor="#6C757D" ncTypography="custom"
          v-bind:resetTrigger="false" ncTooltipText="" verticalWidth="60px"
          v-bind:nucalDataModel="{'type':'NSW','isList':false,'dynamic':false,'structure':[{'type':'string','propName':'text','displayName':'Value'}]}"
          verticalHeight="60px" horizontalWidth="72.4479px" horizontalHeight="37.5347px" ncClickFontColor="#FFFFFF"
          ncFocusFontColor="#FFFFFF" ncHoverFontColor="#FFFFFF" ncClickBorderColor="#4285f4"
          ncDisableFontColor="#FFFFFF" ncFocusBorderColor="#4285f4" ncHoverBorderColor="#4285f4"
          ncDisableBorderColor="transparent" ncClickBackgroundColor="#4285f4" ncFocusBackgroundColor="#4285f4"
          ncHoverBackgroundColor="#4285f4" ncDisableBackgroundColor="#969696" id="adc0600d-2897-4d96-9e3f-3b0575178918"
          v-bind:style="{'width':'69px','height':'27.75px','zIndex':18,'fontSize':'12.375px','maxWidth':'','minWidth':'','tabIndex':'0px','boxShadow':'','fontStyle':'normal','marginTop':'0px','maxHeight':'','minHeight':'','textAlign':'center','fontFamily':'OpenSans-Regular,Open Sans','fontWeight':'normal','lineHeight':'0.7874999999999999','marginLeft':'0px','paddingTop':'','textShadow':'','visibility':'visible','borderStyle':'none','marginRight':'0px','paddingLeft':'','marginBottom':'0px','paddingRight':'','paddingBottom':'','borderTopWidth':'0.5625px','textDecoration':'underline','borderLeftWidth':'0.5625px','borderRightWidth':'0.5625px','horizontalHeight':'21.11326875px','borderBottomWidth':'0.5625px','borderTopLeftRadius':'2.25px','borderTopRightRadius':'2.25px','borderBottomLeftRadius':'2.25px','borderBottomRightRadius':'2.25px'}"/>
        <WOutlineSecondaryButton tag="button" top="1.828010391198044%" left="44.6418991416309%" v-bind:pill="false"
          size="md" text="Team" type="button" v-bind:block="false" color="#FFFFFF" v-bind:snapX="false"
          v-bind:snapY="false" theme="theme--light01" v-bind:squared="false" variant="outline-secondary"
          position="absolute" v-bind:isEnabled="true" background="" borderColor="#6C757D" ncTypography="custom"
          v-bind:resetTrigger="false" ncTooltipText="" verticalWidth="60px"
          v-bind:nucalDataModel="{'type':'NSW','isList':false,'dynamic':false,'structure':[{'type':'string','propName':'text','displayName':'Value'}]}"
          verticalHeight="60px" horizontalWidth="72.4479px" horizontalHeight="37.5347px" ncClickFontColor="#FFFFFF"
          ncFocusFontColor="#FFFFFF" ncHoverFontColor="#FFFFFF" ncClickBorderColor="#4285f4"
          ncDisableFontColor="#FFFFFF" ncFocusBorderColor="#4285f4" ncHoverBorderColor="#4285f4"
          ncDisableBorderColor="transparent" ncClickBackgroundColor="#4285f4" ncFocusBackgroundColor="#4285f4"
          ncHoverBackgroundColor="#4285f4" ncDisableBackgroundColor="#969696" id="6bd8cf4d-a2dc-4f94-b518-717d754386ab"
          v-bind:style="{'width':'69px','height':'27.75px','zIndex':19,'fontSize':'12.375px','maxWidth':'','minWidth':'','tabIndex':'0px','boxShadow':'','fontStyle':'normal','marginTop':'0px','maxHeight':'','minHeight':'','textAlign':'center','fontFamily':'OpenSans-Regular,Open Sans','fontWeight':'normal','lineHeight':'0.7874999999999999','marginLeft':'0px','paddingTop':'','textShadow':'','visibility':'visible','borderStyle':'none','marginRight':'0px','paddingLeft':'','marginBottom':'0px','paddingRight':'','paddingBottom':'','borderTopWidth':'0.5625px','textDecoration':'underline','borderLeftWidth':'0.5625px','borderRightWidth':'0.5625px','horizontalHeight':'21.11326875px','borderBottomWidth':'0.5625px','borderTopLeftRadius':'2.25px','borderTopRightRadius':'2.25px','borderBottomLeftRadius':'2.25px','borderBottomRightRadius':'2.25px'}"/>
        <WOutlineSecondaryButton tag="button" top="1.824190097799511%" left="52.28116058655222%" v-bind:pill="false"
          size="md" text="Shop" type="button" v-bind:block="false" color="#FFFFFF" v-bind:snapX="false"
          v-bind:snapY="false" theme="theme--light01" v-bind:squared="false" variant="outline-secondary"
          position="absolute" v-bind:isEnabled="true" background="" borderColor="#6C757D" ncTypography="custom"
          v-bind:resetTrigger="false" ncTooltipText="" verticalWidth="60px"
          v-bind:nucalDataModel="{'type':'NSW','isList':false,'dynamic':false,'structure':[{'type':'string','propName':'text','displayName':'Value'}]}"
          verticalHeight="60px" horizontalWidth="72.4479px" horizontalHeight="37.5347px" ncClickFontColor="#FFFFFF"
          ncFocusFontColor="#FFFFFF" ncHoverFontColor="#FFFFFF" ncClickBorderColor="#4285f4"
          ncDisableFontColor="#FFFFFF" ncFocusBorderColor="#4285f4" ncHoverBorderColor="#4285f4"
          ncDisableBorderColor="transparent" ncClickBackgroundColor="#4285f4" ncFocusBackgroundColor="#4285f4"
          ncHoverBackgroundColor="#4285f4" ncDisableBackgroundColor="#969696" id="477968f4-2016-44d4-ab00-e101c834487f"
          v-bind:style="{'width':'69px','height':'27.75px','zIndex':20,'fontSize':'12.375px','maxWidth':'','minWidth':'','tabIndex':'0px','boxShadow':'','fontStyle':'normal','marginTop':'0px','maxHeight':'','minHeight':'','textAlign':'center','fontFamily':'OpenSans-Regular,Open Sans','fontWeight':'normal','lineHeight':'0.7874999999999999','marginLeft':'0px','paddingTop':'','textShadow':'','visibility':'visible','borderStyle':'none','marginRight':'0px','paddingLeft':'','marginBottom':'0px','paddingRight':'','paddingBottom':'','borderTopWidth':'0.5625px','textDecoration':'underline','borderLeftWidth':'0.5625px','borderRightWidth':'0.5625px','horizontalHeight':'21.11326875px','borderBottomWidth':'0.5625px','borderTopLeftRadius':'2.25px','borderTopRightRadius':'2.25px','borderBottomLeftRadius':'2.25px','borderBottomRightRadius':'2.25px'}"/>
        <WOutlineSecondaryButton tag="button" top="1.8222799511002445%" left="60.13948497854077%" v-bind:pill="false"
          size="md" text="Pages" type="button" v-bind:block="false" color="#FFFFFF" v-bind:snapX="false"
          v-bind:snapY="false" theme="theme--light01" v-bind:squared="false" variant="outline-secondary"
          position="absolute" v-bind:isEnabled="true" background="" borderColor="#6C757D" ncTypography="custom"
          v-bind:resetTrigger="false" ncTooltipText="" verticalWidth="60px"
          v-bind:nucalDataModel="{'type':'NSW','isList':false,'dynamic':false,'structure':[{'type':'string','propName':'text','displayName':'Value'}]}"
          verticalHeight="60px" horizontalWidth="72.4479px" horizontalHeight="37.5347px" ncClickFontColor="#FFFFFF"
          ncFocusFontColor="#FFFFFF" ncHoverFontColor="#FFFFFF" ncClickBorderColor="#4285f4"
          ncDisableFontColor="#FFFFFF" ncFocusBorderColor="#4285f4" ncHoverBorderColor="#4285f4"
          ncDisableBorderColor="transparent" ncClickBackgroundColor="#4285f4" ncFocusBackgroundColor="#4285f4"
          ncHoverBackgroundColor="#4285f4" ncDisableBackgroundColor="#969696" id="a822e951-fad8-4d4c-bf92-633b4d8479ad"
          v-bind:style="{'width':'69px','height':'27.75px','zIndex':21,'fontSize':'12.375px','maxWidth':'','minWidth':'','tabIndex':'0px','boxShadow':'','fontStyle':'normal','marginTop':'0px','maxHeight':'','minHeight':'','textAlign':'center','fontFamily':'OpenSans-Regular,Open Sans','fontWeight':'normal','lineHeight':'0.7874999999999999','marginLeft':'0px','paddingTop':'','textShadow':'','visibility':'visible','borderStyle':'none','marginRight':'0px','paddingLeft':'','marginBottom':'0px','paddingRight':'','paddingBottom':'','borderTopWidth':'0.5625px','textDecoration':'underline','borderLeftWidth':'0.5625px','borderRightWidth':'0.5625px','horizontalHeight':'21.11326875px','borderBottomWidth':'0.5625px','borderTopLeftRadius':'2.25px','borderTopRightRadius':'2.25px','borderBottomLeftRadius':'2.25px','borderBottomRightRadius':'2.25px'}"/>
      </NucGroupElement>
    </NucGridCell>
  </NucGridPage>
</template>
<script>
export default {
  name: 'Screen1',
  data() {
    return {};
  },
  props: {},
  created() {},
  mounted() {},
  computed: {},
  methods: {},
  watch: {},
};
</script>

<style scoped></style>